added battery object
tue-robotics/tue_robocup pull request #1070
Opened 2021-02-06 09:53 UTC by PetervDooren

2021-02-06 10:15 UTC, MatthijsBurgh requested changes
Please add some docstrings.

This only works for HERO. As the battery topics on the TUe robots are different. That should also be documented.

Also this implementation assumes that the last message is indeed recent. If the publisher stops publishing, the last message gets outdated. I am fine with the implementation, but it should documented.

Final question: What is going to be used for?

2021-02-06 10:16 UTC, PetervDooren commented
Preventing the robot from driving off while it is charging:)

2021-02-06 10:38 UTC, MatthijsBurgh requested changes

2021-02-06 10:38 UTC, MatthijsBurgh commented on robot_skills/src/robot_skills/battery.py
> +        self.battery_sub = rospy.Subscriber("battery", BatteryState, self.battery_callback)
Please use https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/robot_part.py#L130

2021-02-16 19:54 UTC, MatthijsBurgh approved these changes

2021-02-17 08:06 UTC, merged