Feature/use battery part
tue-robotics/tue_robocup pull request #1088
Opened 2021-02-23 20:24 UTC by PetervDooren

Created for people who occasionally forget that the robot is charging :)

2021-04-27 17:30 UTC, PetervDooren commented
I moved a lot of checks to a new state 'prepare drive' which ensures that the robot is ready to start driving. The one thing that could not be placed here is going to the driving pose, because that might change based on the distance we need to drive.

This does add the assumption that the things in the 'prepare drive' state only need to be checked at the start of navigation and cannot be changed during the process. i.e. noone plugs in the robot while navigating and noone uses and then releases the head.

2021-04-27 19:53 UTC, MatthijsBurgh requested changes
Also fix CI

2021-04-27 19:53 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/navigation/navigation.py
> +                    if tstart - rospy.Time.now() < rospy.Duration.from_sec(self.timeout):
I am not sure this needs to be and `rospy.duration`. Maybe a float/int would also work

2021-04-27 19:53 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/navigation/navigation.py
> +                    if tstart - rospy.Time.now() < rospy.Duration.from_sec(self.timeout):
First part is going to b e negative.... I don't think that should be the case. Also I prefer now > start+timeout

2021-04-27 19:53 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/navigation/navigation.py
> +                return 'abort'
This code is reaced when not charging anymore. Am I correct? That is not matching the code.

2021-04-27 19:53 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/navigation/navigation.py
> +    def __init__(self, robot, breakout_function, blocked_timeout = 4, reset_pose=True):
No space around equal sings in default arguments

2021-07-27 22:32 UTC, MatthijsBurgh requested changes
CI fails on missing `reset_head`

2021-07-27 22:32 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/navigation/navigation.py
> -    def __init__(self, robot, breakout_function, blocked_timeout=4, reset_head=True, reset_pose=True):
Why dropping this? Is this only obsolete for HERO or all robots?

2024-03-22 09:33 UTC, closed without merging

2024-03-22 10:18 UTC, MatthijsBurgh commented
I think we can delete the branch. GH will still keep the diff.