Add files via upload
tue-robotics/tue_robocup pull request #1115
Opened 2021-05-11 18:31 UTC by PetervDooren

Version 1 of the grasp detection script.

2021-05-25 19:03 UTC, PetervDooren commented
To run the example/test: navigate to the robot_skills/examples folder ("roscd robot_skills/examples") and run "python example_grasp_detector.py"

2021-05-26 08:44 UTC, MatthijsBurgh requested changes

2021-05-31 13:59 UTC, MatthijsBurgh commented on robot_skills/src/robot_skills/arm/grasp_detector.py
> +        self.measuring_for = 15.to_sec()
This should be a rospy Duration
```suggestion
        self.measuring_for = rospy.Duration(15)
```

2021-06-01 20:36 UTC, MatthijsBurgh commented on robot_skills/src/robot_skills/arm/grasp_detector.py
> +        if not (sum(self.msg_list)/len(self.msg_list)) < self.threshold_torque_y:
```suggestion
        if not sum(self.msg_list)/len(self.msg_list) < self.threshold_torque_y:
```

2024-03-22 09:33 UTC, closed without merging