Fix(Place)
tue-robotics/tue_robocup pull request #1170
Opened 2022-04-25 12:31 UTC by PetervDooren

Still requires testing. Have not been able to place an object yet.

2022-04-25 15:48 UTC, MatthijsBurgh requested changes

2022-04-25 15:48 UTC, MatthijsBurgh commented on robot_skills/src/robot_skills/robot.py
> +        self.base_link_frame = "base_link"
This is robot_specific. tf_prefix has been dropped from TF2, but this means that the urdf can't have any namespace. So `amigo/base_link` is still very valid.

So this should be configurable.

2022-12-02 14:38 UTC, PetervDooren commented
Tested on robot, robot was able to place a fanta on the table

2022-12-23 14:31 UTC, PetervDooren commented
Ping @MatthijsBurgh

2022-12-23 15:00 UTC, MatthijsBurgh approved these changes

2023-02-04 08:55 UTC, merged