feat(restaurant): Revive for 2022
tue-robotics/tue_robocup pull request #1193
Opened 2022-06-18 12:01 UTC by reinzor

2022-06-18 13:44 UTC, reinzor commented
Please squash the PR

2022-06-20 11:29 UTC, MatthijsBurgh requested changes

2022-06-20 11:29 UTC, MatthijsBurgh commented on challenge_restaurant/src/challenge_restaurant/restaurant.py
> +                                       "images/waving.jpg", seconds=10),
This is not going to work. Use rospack get path.

2022-06-20 11:29 UTC, MatthijsBurgh commented on challenge_restaurant/src/challenge_restaurant/store_waypoint.py
> +
Use HERO or `get_robot`

2022-07-02 12:19 UTC, merged