Receptionist fix drink designators
tue-robotics/tue_robocup pull request #1200
Opened 2022-06-23 10:39 UTC by PetervDooren

2022-06-24 13:03 UTC, MatthijsBurgh requested changes

2022-06-24 13:03 UTC, MatthijsBurgh commented on challenge_receptionist/src/challenge_receptionist/learn_guest.py
> +                                   transitions={'done': 'SAY_DRINK_CORRECT_NAME'})
What is happening here? We get the value of one designator and write it to another one?

2022-06-24 13:05 UTC, MatthijsBurgh requested changes

2022-06-24 13:05 UTC, MatthijsBurgh commented on challenge_receptionist/src/challenge_receptionist/learn_guest.py
> +        guest_drink_name_des = ds.FieldOfHMIResult(guest_drink_hmi_des, semantics_path='drink', name='guest_drinkname')
This should get you the info from the HMIResult...

2022-06-24 13:50 UTC, MatthijsBurgh commented
Redefining input vars is so wrong. So keeping that while writing some extra code to workaround this mess is not good.

2022-06-24 13:52 UTC, MatthijsBurgh commented
I recommend to go for alternative PR #1201

2022-06-28 17:55 UTC, LarsJanssenTUe commented
See https://github.com/tue-robotics/tue_robocup/pull/1201

2022-06-28 17:55 UTC, closed without merging