Fix/grasping benchmark
tue-robotics/tue_robocup pull request #1251
Opened 2022-10-21 13:47 UTC by PetervDooren

2022-10-21 22:02 UTC, MatthijsBurgh requested changes
One small change

2022-10-21 22:02 UTC, MatthijsBurgh commented on robot_smach_states/benchmark/benchmark_grasping.py
> +                    frame_stamped = entity.pose  # type: VectorStamped
Change the typehinting

2022-11-22 16:03 UTC, PetervDooren commented on robot_smach_states/benchmark/benchmark_grasping.py
> +                    frame_stamped = entity.pose  # type: VectorStamped
```suggestion
                    frame_stamped = entity.pose  # type: FrameStamped
```

2022-11-24 09:23 UTC, MatthijsBurgh approved these changes

2022-12-17 13:40 UTC, merged