Rpo2023 challenge storing groceries
tue-robotics/tue_robocup pull request #1300
Opened 2023-05-06 11:24 UTC by P-ict0

2023-05-06 11:29 UTC, MatthijsBurgh commented on challenge_storing_groceries/src/challenge_storing_groceries/inspect_shelves.py
> +if __name__ == '__main__':
```suggestion
if __name__ == "__main__":
```

2023-05-06 11:31 UTC, MatthijsBurgh commented on challenge_storing_groceries/src/challenge_storing_groceries/manipulate_machine.py
> +                                   transitions={'succeeded': 'succeeded',
Not sure this should result in succeeded. Probably failed is better.

2023-05-10 13:05 UTC, PetervDooren requested changes
Few clean up things. Most are related to testcases which can be defered to another PR. Other than that, we should test this once in Impuls and merge it.

2023-05-10 13:05 UTC, PetervDooren commented on challenge_storing_groceries/src/challenge_storing_groceries/manipulate_machine.py
> +    sm.execute()
double check names and usage string. Or remove here and fix in https://github.com/tue-robotics/tue_robocup/pull/1270

2023-05-10 13:05 UTC, PetervDooren commented on challenge_storing_groceries/src/challenge_storing_groceries/near_object_designator.py
> +    nearObjectDes.resolve()
double check names and usage string. Or remove here and fix in https://github.com/tue-robotics/tue_robocup/pull/1270

2023-05-10 13:05 UTC, PetervDooren commented on challenge_storing_groceries/src/challenge_storing_groceries/open_door.py
> +# noinspection PyUnresolvedReferences
Do we recall the reason for this? If not lets remove this.

2023-05-13 09:40 UTC, MatthijsBurgh commented on robocup_knowledge/src/robocup_knowledge/environments/impuls/challenge_storing_groceries.py
> +object_types = [obj["name"] for obj in common.objects] #TODO unused variable?
```suggestion
object_shelves = ["shelf3", "shelf4", "shelf5"]  # TODO unused variable?
object_types = [obj["name"] for obj in common.objects]  # TODO unused variable?
```

2023-05-13 11:44 UTC, PetervDooren commented on challenge_storing_groceries/src/challenge_storing_groceries/open_door.py
> +# noinspection PyUnresolvedReferences
open door needs a lot of work (probably a complete refactor) anyway. So I am fine either way.

2023-05-13 12:03 UTC, PetervDooren approved these changes

2023-05-13 12:10 UTC, merged

2023-05-13 12:50 UTC, MatthijsBurgh commented
@PetervDooren changes in `robot_smach_states` should be applied to the remainder branch. This has created merge conflicts