(Place) Removed useless motion of arm and improved docs
tue-robotics/tue_robocup pull request #1317
Opened 2023-05-29 17:45 UTC by P-ict0

2023-05-29 20:19 UTC, PetervDooren approved these changes
Depending on the implementation used we may need to put prepare place where it is now commented. It would be nice to figure that out fast.

2023-06-03 07:10 UTC, PetervDooren commented
It is already broken for robots other than Hero. We don't have the infrastructure to properly support 'any' robot.
What happened here is that the functionality of PUT was implicitly changed due to switching to collision avoidance. As long as the other robots keep a similar functionality it will remain consistent.

2023-06-03 07:53 UTC, PetervDooren submitted a review, later dismissed

2023-06-03 08:28 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/manipulation/place.py
>          assert(arm.resolve_type == PublicArm or type(arm) == PublicArm)
Should use `check_resolve_type`

2023-06-03 10:00 UTC, MatthijsBurgh requested changes

2023-06-03 10:00 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/manipulation/place.py
> -        assert(arm.resolve_type == PublicArm or type(arm) == PublicArm)
Sorry, use `check_type`

2023-06-03 11:58 UTC, PetervDooren commented
@MatthijsBurgh, the check_type is a correct improvement but it has nothing to do with the changes in this PR. The changes here are fine and can be merged without worrying about changing check type as well. 
If we want to change this check type I suggest doing it in a small PR rather than delaying this one any further.

2023-06-03 12:34 UTC, MatthijsBurgh commented on robot_smach_states/src/robot_smach_states/manipulation/place.py
> +        assert(check_type(arm, PublicArm) or isinstance(arm, PublicArm))
```suggestion
        check_type(item_to_place, Entity)
        check_type(arm, PublicArm)
```

2023-06-03 12:36 UTC, MatthijsBurgh commented
@PetervDooren changes were already made to these lines. So therefore the changes need to be correct and complete.

I applied the changes.

2023-06-03 13:16 UTC, PetervDooren commented
> @PetervDooren changes were already made to these lines. So therefore the changes need to be correct and complete.
> 
> I applied the changes.

No they were not. A commented line was removed. That does not make Rodrigo responsible for fixing all the lines near that. That is not how this works.

2023-06-03 13:17 UTC, PetervDooren approved these changes

2023-06-03 13:18 UTC, merged